#! /bin/bash

#choose-release-tag
#by Julian Sangillo
#Return the dev, test, or stable release tag if the checked out branch is the dev, test, or stable branch respectively.

showHelp() {
	echo "Usage: choose-release-tag [options...]";
	echo "Return the dev, test, or stable release tag if the checked out branch is the dev, test, or stable branch respectively.";
	echo "	";
	echo "Options: ";
	echo "	-s	Sets the reference to your stable branch to the string";
	echo "		provided. Default is 'master'.";
	echo "	-t	Sets the reference to your test branch to the string";
	echo "		provided. Default is 'test'.";
	echo "	-d	Sets the reference to your dev branch to the string";
	echo "		provided. Default is 'develop'.";
	echo "	-S	Provide the release tag for a version on a stable branch.";
	echo "		Default means no release tag.";
	echo "	-T	Provide the release tag for a version on a test branch.";
	echo "		Default is 'TEST'.";
	echo "	-D	Provide the release tag for a version on a dev branch.";
	echo "		Default is 'DEVELOP'."
} >&2

STABLE_BRANCH='master';
TEST_BRANCH='test';
DEV_BRANCH='develop';
STABLE_TAG='';
TEST_TAG='TEST';
DEV_TAG='DEVELOP';

while getopts ":s:t:d:S:T:D:" opt; do
	case "${opt}" in
		s) STABLE_BRANCH=$OPTARG ;;
		t) TEST_BRANCH=$OPTARG ;;
		d) DEV_BRANCH=$OPTARG ;;
		S) STABLE_TAG=$OPTARG ;;
		T) TEST_TAG=$OPTARG ;;
		D) DEV_TAG=$OPTARG ;;
		*)
			showHelp;
			exit 1
			;;
	esac
done
shift $((OPTIND-1));

log "stable-branch = $STABLE_BRANCH";
log "test-branch = $TEST_BRANCH";
log "dev-branch = $DEV_BRANCH";
log "stable-tag = $STABLE_TAG";
log "test-tag = $TEST_TAG";
log "dev-tag = $DEV_TAG";

fetchCurrentBranch() {
	echo "$(git branch --show-current)"
}

chooseReleaseTag() {
	log 'Choosing release tag ...';

	local branch="$(fetchCurrentBranch)" || exit $?;
	
	if [ "$branch" = "$DEV_BRANCH" ]; then
		local tag="$DEV_TAG";
	elif [ "$branch" = "$TEST_BRANCH" ]; then
		local tag="$TEST_TAG";
	elif [ "$branch" = "$STABLE_BRANCH" ]; then
		local tag="$STABLE_TAG";
	else
		log "Could not choose release tag! Unknown branch '$branch'";
		exit 32
	fi
	
	echo $tag
}

RELEASE_TAG="$(chooseReleaseTag)" || exit $?;

log 'Release tag chosen successfully';
log "Release tag = $RELEASE_TAG";

echo $RELEASE_TAG;
exit 0