#! /bin/bash

#get-latest-version
#by Julian Sangillo <juliansangillo@gmail.com>
#Gets the latest version from the latest tag that exists in repo.

getLatestVersion() {
	log "Getting the latest version from repo ...";
	
	local latest="$(git describe --abbrev=0 --tags 2>/dev/null | tr -d 'v')"
	if [ -z $latest ]; then
		log "Latest version doesn't exist.";
	else
		log "Latest version found. Revision: $latest";
		
		local revisions=($(split . $latest));
		local last=${#revisions[@]}-1
		if ! [[ "${revisions[$last]}" =~ ^[0-9]+$ ]]; then
			log "Stripping release tag ...";
			revisions[$last]='';
		fi
		
		latest=$(join . ${revisions[@]});
		log "Latest revision: $latest";
	fi
	
	echo $latest
}

echo "$(getLatestVersion)";
exit 0;