#! /bin/bash

#get-latest-version
#by Julian Sangillo <juliansangillo@gmail.com>
#Gets the latest version from the latest tag that exists in the current git branch.

getLatestVersion() {
	log "Getting the latest version from repo ...";
	
	local latest="$(git describe --abbrev=0 2>/dev/null | tr -d 'v')"
	if [ -z $latest ]; then
		log "Latest version doesn't exist.";
	else
		log "Latest version found. Revision: $latest";
	fi
	
	echo $latest
}

echo "$(getLatestVersion)";
exit 0;