#! /bin/bash

#join-on-period
#by Julian Sangillo
#Loads function to join multiple arguments into a string on a delimeter and returning that string. Usage: join <delim> [args...]

join() {
	local IFS="$1";
	shift;
	echo "$*"
}